### ISSUE TITLE
Fix codesandbox of complex examples

### ISSUE THREAD

**Issue by stropitek** [zakodium/react-plot-docs#11]
Examples which are not working:
- Making relative imports
- Making requests to fetch static data (jcamp files mostly)

**Comment by targos** [comment]
I don't think we should have relative imports in examples. This hides away code that is necessary for the example to work.

**Comment by stropitek** [comment]
I generally agree. But we shouldn't clutter the demo's code with data preprocessing stuff. Maybe we should fetch the raw x,y points from a server.

**Comment by lpatiny** [comment]
I would like to give real case examples and most of the time people have no idea how to convert a jcamp, netcdf, even tsv to x,y points. Having a place to write this documentation seems useful to me and therefore have this preprocessing step.

**Comment by stropitek** [comment]
Okay if react-plot-docs is the place we want to document that then why not.

But examples should focus on something specific. If it's on how to create a plot with a rectangular zoom then it's distracting to add all the data preprocessing logic to the demo.

![image](https://user-images.githubusercontent.com/4118690/157439724-bfcf715f-ebad-4059-8cba-a8dc48da08b1.png)
